### ISSUE TITLE
Crash on fakeblock creation

### ISSUE THREAD

**Issue by RayanBn** [IWareQ/FakeInventories#1]
I try to use the library, but I crash every time I instantiate a new FakeInventory. So I did a little research and found that the crash was coming from this line:
this.fakeBlock.create(player, this.getTitle());
in the onOpen function of the FakeInventory class. However, I don't know why this crash occurs.

**Comment by IWareQ** [comment]
Hi, can you send the debug log and the core name on which the plugin is installed?

**Comment by RayanBn** [comment]
Hi, here is the debug log and i use PowerNukkit :
```
[FATAL] Exception happened while ticking server

"main" prio=5 Id=1 RUNNABLE
        at java.management@20.0.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
        at java.management@20.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:540)
        at java.management@20.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:527)
        at app//cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:175)
        at app//cn.nukkit.Server.tickProcessor(Server.java:1184)
        at app//cn.nukkit.Server.start(Server.java:1133)
        at app//cn.nukkit.Server.<init>(Server.java:960)
        at app//cn.nukkit.Nukkit.main(Nukkit.java:160)


"Reference Handler" daemon prio=10 Id=9 RUNNABLE
        at java.base@20.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
        at java.base@20.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
        at java.base@20.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)


"Finalizer" daemon prio=8 Id=10 WAITING on java.lang.ref.NativeReferenceQueue$Lock@24d25c43
        at java.base@20.0.1/java.lang.Object.wait0(Native Method)
        -  waiting on java.lang.ref.NativeReferenceQueue$Lock@24d25c43
        at java.base@20.0.1/java.lang.Object.wait(Object.java:366)
        at java.base@20.0.1/java.lang.Object.wait(Object.java:339)
        at java.base@20.0.1/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
        at java.base@20.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
        at java.base@20.0.1/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
        at java.base@20.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
```

**Comment by RayanBn** [comment]
I think this is more interessting output log :
```
java.lang.NoClassDefFoundError: me/iwareq/fakeinventories/FakeInventory
        at niro.Blocks.Crates.VoteCrate.onTouch(VoteCrate.java:78) ~[?:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:3105) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:3065) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handleUseItem(InventoryTransactionProcessor.java:536) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handle(InventoryTransactionProcessor.java:57) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handle(InventoryTransactionProcessor.java:46) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.DataPacketManager.processPacket(DataPacketManager.java:47) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3483) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:240) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:95) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:239) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.tick(Server.java:1278) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1152) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.start(Server.java:1133) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.<init>(Server.java:960) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-1.20.0-r2.jar:?]
Caused by: java.lang.ClassNotFoundException: me.iwareq.fakeinventories.FakeInventory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 16 more
```

**Comment by IWareQ** [comment]
Are you sure that the FakeInventories plugin is installed and running successfully? Judging by the error, it seems to me that the plugin is not installed

**Comment by RayanBn** [comment]
yes, I added this to my pom.xml:
```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.IWareQ</groupId>
            <artifactId>FakeInventories</artifactId>
            <version>v1.1.4</version>
        </dependency>
    </dependencies>
  ```

**Comment by RayanBn** [comment]
ok, I just found it, I had missed the installation :/
But this time, when I go back to the example, I get this error:
```
An error occurred whilst handling InventoryTransactionPacket for NexosXY
java.lang.NullPointerException: Fake block for: CHEST not found
        at me.iwareq.fakeinventories.FakeInventories.getFakeBlock(FakeInventories.java:21) ~[?:?]
        at me.iwareq.fakeinventories.FakeInventory.<init>(FakeInventory.java:33) ~[?:?]
        at niro.Blocks.Crates.VoteCrate.onTouch(VoteCrate.java:78) ~[?:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:3105) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:3065) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handleUseItem(InventoryTransactionProcessor.java:536) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handle(InventoryTransactionProcessor.java:57) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.processor.InventoryTransactionProcessor.handle(InventoryTransactionProcessor.java:46) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.process.DataPacketManager.processPacket(DataPacketManager.java:47) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3483) ~[PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:240) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:95) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:239) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.tick(Server.java:1278) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1152) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.start(Server.java:1133) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Server.<init>(Server.java:960) [PowerNukkitX-1.20.0-r2.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-1.20.0-r2.jar:?]
```

**Comment by IWareQ** [comment]
drop me you file: VoteCrate.java

**Comment by RayanBn** [comment]
github dont support .java file so here is my code :
```java
package niro.Blocks.Crates;

import cn.nukkit.Player;
import cn.nukkit.block.BlockTransparentMeta;
import cn.nukkit.block.customblock.CustomBlock;
import cn.nukkit.block.customblock.CustomBlockDefinition;
import cn.nukkit.block.customblock.data.*;
import cn.nukkit.blockproperty.BlockProperties;
import cn.nukkit.blockproperty.BooleanBlockProperty;
import cn.nukkit.event.player.PlayerInteractEvent;
import cn.nukkit.inventory.InventoryType;
import cn.nukkit.item.Item;
import me.iwareq.fakeinventories.FakeInventory;
import org.jetbrains.annotations.NotNull;

import javax.annotation.Nullable;

public class VoteCrate extends BlockTransparentMeta implements CustomBlock {
    @NotNull
    @Override
    public String getNamespaceId() {
        return "pnx:votecrate";
    }

    @Override
    public String getName() {
        return CustomBlock.super.getName();
    }

    @Override
    public int getId() {
        return CustomBlock.super.getId();
    }

    @NotNull
    @Override
    public BlockProperties getProperties() {
        return new BlockProperties(
                new BooleanBlockProperty("open", false)
        );
    }

    @Override
    public CustomBlockDefinition getDefinition() {
        return CustomBlockDefinition
                .builder(this, "votecrate")
                .blockTags("VoteCrate")
                .geometry(new Geometry("geometry.votecrate")
                        .boneVisibility("lower", true)
                        .boneVisibility("upper", true)
                )
                .build();
    }

    @Override
    public int getItemMaxStackSize() {
        return 64;
    }

    @Override
    public int onTouch(@Nullable Player player, PlayerInteractEvent.Action action) {
        if (player == null || action != PlayerInteractEvent.Action.RIGHT_CLICK_BLOCK) {
            return 0;
        }

        FakeInventory inventory = new FakeInventory(InventoryType.CHEST, "custom title");

        inventory.setDefaultItemHandler((item, event) -> {
            event.setCancelled(true);

            Player target = event.getTransaction().getSource();

            target.sendMessage("is default item handler");
        });

        inventory.addItem((item, event) -> {
            event.setCancelled(true);

            Player target = event.getTransaction().getSource();

            target.sendMessage("is custom item handler in addItem method");

            target.removeWindow(inventory);
        }, Item.get(Item.IRON_BLOCK), Item.get(Item.IRON_BAR));

        inventory.setItem(5, Item.get(Item.DIAMOND), (item, event) -> {
            event.setCancelled(true);

            Player target = event.getTransaction().getSource();

            target.sendMessage("is custom item handler");

            target.removeWindow(inventory);
        });

        player.addWindow(inventory);

        return 0;
    }
}

```

**Comment by IWareQ** [comment]
hmm, are you sure that FakeInventions enabled without errors? I just checked - everything is working, inventory is being created and opened

**Comment by RayanBn** [comment]
I've checked everything and it all seems fine. Do we agree that all I have to do to install the library is update my pom.xml file and add the library during compilation?

**Comment by RayanBn** [comment]
can you send me little project were FakeInventories work for you ?

**Comment by RayanBn** [comment]
When i do this :
```java
        Map<InventoryType, FakeBlock> FAKE_BLOCKS = new EnumMap(InventoryType.class);
        FakeBlock fake = FAKE_BLOCKS.get(InventoryType.CHEST);
        if (fake == null) {
            System.out.println("fake is null");
            return 0;
        }
```

i always have this line executed :
```java
System.out.println("fake is null");
```

**Comment by RayanBn** [comment]
When i do this :
```java
Map<InventoryType, FakeBlock> FAKE_BLOCKS = new EnumMap(InventoryType.class);
        FAKE_BLOCKS.put(InventoryType.CHEST, new SingleFakeBlock(54, "Chest"));
        FakeBlock fake = FAKE_BLOCKS.get(InventoryType.CHEST);

        if (fake == null) {
            System.out.println("fake is null");
            return 0;
        }
```

this line is never executed :
```java
System.out.println("fake is null");
```
so its the onEnable function but i dont know why

**Comment by IWareQ** [comment]
It's strange that it gives you null, although there is such a block, a little later I will transfer this block of code to onLoad and write a test plugin for PowerNukkitX
